# Generated by Django 5.0.1 on 2024-01-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishgood',
            name='id',
        ),
        migrations.AlterField(
            model_name='finishgood',
            name='Referencia',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
