# Generated by Django 5.0.1 on 2024-02-02 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0002_remove_finishgood_id_alter_finishgood_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('Referencia', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Estado', models.CharField(max_length=100)),
                ('Stock', models.FloatField(blank=True)),
                ('Necesidad', models.IntegerField(blank=True)),
                ('Url', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField()),
                ('finish_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cps.finishgood')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cps.componente')),
            ],
            options={
                'unique_together': {('finish_good', 'componente')},
            },
        ),
    ]
