# Generated by Django 5.0.1 on 2024-02-05 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cps', '0003_componente_bom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='id',
        ),
        migrations.RemoveField(
            model_name='finishgood',
            name='Stock',
        ),
        migrations.AlterField(
            model_name='bom',
            name='finish_good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cps.finishgood'),
        ),
    ]
